language: ruby
rvm:
  - 2.3.1
cache: bundler

env:
  global:
    - CXX=g++-4.8

services:
  - redis-server

addons:
  postgresql: 9.3
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - bundle exec rake db:create db:migrate db:seed
