language: ruby
rvm:
  - 2.5.1
cache: bundler

env:
  global:
    - CXX=g++-4.8

services:
  - redis-server

addons:
  postgresql: '10'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create db:migrate db:seed

script:
  - bundle exec rake
  - bundle exec rubocop
