language: elixir

elixir:
  - 1.3.1

node_js:
  - "6"

cache:
  directories:
    - _build
    - deps
    - node_modules

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: '9.4'

before_script:
  - npm install
  - npm run deploy

before_script:
  - npm run build
